#!/bin/bash
 
#PBS -l walltime=8:00:00,select=1:ncpus=1:ngpus=1:mem=32gb
#PBS -N shakeServer
#PBS -A <ACCOUNT>
#PBS -m abe
#PBS -M <EMAIL>
#PBS -o output_server.txt
#PBS -e error_server.txt
 
################################################################################
 
module load gcc
module load cuda

echo $PBS_NODEFILE;cat $PBS_NODEFILE

echo ${PYTHONPATH}
cd $PBS_O_WORKDIR

./run_shake.sh 0
