#!/bin/bash
 
#PBS -l walltime=4:00:00,select=1:ncpus=1:ngpus=1:mem=32gb
#PBS -J 0-9
#PBS -N cifarArray
#PBS -A 
#PBS -m abe
#PBS -M 
#PBS -o output_^array_index^.txt
#PBS -e error_^array_index^.txt
 
################################################################################
 
module load gcc
module load cuda

echo I am job index: $PBS_ARRAY_INDEX

echo ${PYTHONPATH}
cd $PBS_O_WORKDIR

./run_cifar.sh $(($PBS_ARRAY_INDEX +1))
